### ISSUE TITLE
What‘s the use of wipo

### ISSUE THREAD

**Issue by yaojl2006** [kermitt2/grobid-example#6]
Hi,
I find there's a document **org/wipo** in the lib and I don't find where it is used. Actually I can run grobid as 
a java library well without this document. Could you tell me what this part used to do? 
Thank you.

**Comment by kermitt2** [comment]
Hello! It is used in GROBID for tokenizing eastern language text, so in Chinese, Japanese and Korean. 
So if there is no such language in the input (according to the language recognizer), then I guess those classes will not be uploaded and it will works well without this dependency.

**Comment by yaojl2006** [comment]
Hi，
I‘ve got it.
Thank you！
